cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sly.fa >../associated_data/KaKs_m6A/ath-sly_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sly.fa >../associated_data/KaKs_m6A/ath-sly_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sly_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sly_Chloroplastida/kaks_ath-sly_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sly.fa >../associated_data/KaKs_m6A/ath-sly_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sly.fa >../associated_data/KaKs_m6A/ath-sly_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sly_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sly_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sly_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sly_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-sly_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sly_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/ath-sly_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sly_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sly_Embryophyta/kaks_ath-sly_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sly.fa >../associated_data/KaKs_m6A/ath-sly_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sly.fa >../associated_data/KaKs_m6A/ath-sly_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sly_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sly_Spermatophyta/kaks_ath-sly_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sly.fa >../associated_data/KaKs_m6A/ath-sly_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sly.fa >../associated_data/KaKs_m6A/ath-sly_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sly_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sly_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sly_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sly_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/ath-sly_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sly_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/ath-sly_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sly_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sly_Angiosperm/kaks_ath-sly_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-pvu_Chloroplastida/kaks_ath-pvu_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sbi_Chloroplastida/kaks_ath-sbi_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/ath-ata_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/ath-ata_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-ata_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-ata_Chloroplastida/kaks_ath-ata_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-pvu_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-pvu_Embryophyta/kaks_ath-pvu_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-sbi_Chloroplastida/kaks_sly-sbi_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/ath-osa_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/ath-osa_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-osa_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-osa_Chloroplastida/kaks_ath-osa_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-pvu_Spermatophyta/kaks_ath-pvu_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sbi_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sbi_Embryophyta/kaks_ath-sbi_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/ath-gar_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/ath-gar_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-gar_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-gar_Chloroplastida/kaks_ath-gar_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/ath-pvu_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-pvu_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-pvu_Angiosperm/kaks_ath-pvu_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/ath-ata_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/ath-ata_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-ata_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-ata_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-ata_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-ata_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-ata_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-ata_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/ath-ata_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-ata_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-ata_Embryophyta/kaks_ath-ata_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sbi_Spermatophyta/kaks_ath-sbi_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/ath-osa_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/ath-osa_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-osa_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-osa_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-osa_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-osa_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-osa_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-osa_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/ath-osa_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-osa_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-osa_Embryophyta/kaks_ath-osa_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-sbi_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-sbi_Embryophyta/kaks_sly-sbi_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/ath-sbi_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-sbi_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-sbi_Angiosperm/kaks_ath-sbi_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/ath-ata_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/ath-ata_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-ata_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-ata_Spermatophyta/kaks_ath-ata_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/ath-osa_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/ath-osa_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-osa_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-osa_Spermatophyta/kaks_ath-osa_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-sbi_Spermatophyta/kaks_sly-sbi_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/ath-ata_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/ath-ata_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-ata_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-ata_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-ata_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-ata_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/ath-ata_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-ata_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/ath-ata_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-ata_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-ata_Angiosperm/kaks_ath-ata_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/ath-osa_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/ath-osa_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-osa_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-osa_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-osa_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-osa_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/ath-osa_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-osa_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/ath-osa_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-osa_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-osa_Angiosperm/kaks_ath-osa_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/ath-gar_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/ath-gar_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-gar_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-gar_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-gar_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-gar_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-gar_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-gar_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/ath-gar_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-gar_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-gar_Embryophyta/kaks_ath-gar_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/sbi.fa >../associated_data/KaKs_m6A/sly-sbi_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-sbi_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-sbi_Angiosperm/kaks_sly-sbi_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/ath-gar_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/ath-gar_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-gar_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-gar_Spermatophyta/kaks_ath-gar_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/ath.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/ath-gar_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/ath.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/ath-gar_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/ath-gar_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/ath-gar_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/ath-gar_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/ath-gar_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/ath-gar_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/ath-gar_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/ath-gar_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/ath-gar_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/ath-gar_Angiosperm/kaks_ath-gar_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sly-osa_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sly-osa_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-osa_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-osa_Chloroplastida/kaks_sly-osa_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sly-osa_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sly-osa_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-osa_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-osa_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-osa_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-osa_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-osa_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-osa_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sly-osa_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-osa_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-osa_Embryophyta/kaks_sly-osa_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sly-osa_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sly-osa_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-osa_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-osa_Spermatophyta/kaks_sly-osa_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sly-osa_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sly-osa_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-osa_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-osa_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-osa_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-osa_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sly-osa_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-osa_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sly-osa_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-osa_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-osa_Angiosperm/kaks_sly-osa_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sly-ata_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sly-ata_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-ata_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-ata_Chloroplastida/kaks_sly-ata_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sly-gar_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sly-gar_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-gar_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-gar_Chloroplastida/kaks_sly-gar_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-osa_Chloroplastida/kaks_sbi-osa_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-gar_Chloroplastida/kaks_sbi-gar_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-pvu_Chloroplastida/kaks_sly-pvu_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-pvu_Chloroplastida/kaks_sbi-pvu_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sly-ata_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sly-ata_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-ata_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-ata_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-ata_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-ata_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-ata_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-ata_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sly-ata_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-ata_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-ata_Embryophyta/kaks_sly-ata_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-osa_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-osa_Embryophyta/kaks_sbi-osa_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sly-gar_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sly-gar_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-gar_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-gar_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-gar_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-gar_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-gar_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-gar_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sly-gar_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-gar_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-gar_Embryophyta/kaks_sly-gar_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sly-ata_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sly-ata_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-ata_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-ata_Spermatophyta/kaks_sly-ata_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-gar_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-gar_Embryophyta/kaks_sbi-gar_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-pvu_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-pvu_Embryophyta/kaks_sly-pvu_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sly-ata_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sly-ata_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-ata_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-ata_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-ata_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-ata_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sly-ata_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-ata_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sly-ata_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-ata_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-ata_Angiosperm/kaks_sly-ata_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-osa_Spermatophyta/kaks_sbi-osa_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-pvu_Embryophyta/kaks_sbi-pvu_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sly-gar_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sly-gar_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-gar_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-gar_Spermatophyta/kaks_sly-gar_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-gar_Spermatophyta/kaks_sbi-gar_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/osa.fa >../associated_data/KaKs_m6A/sbi-osa_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-osa_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-osa_Angiosperm/kaks_sbi-osa_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sly-gar_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sly-gar_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-gar_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-gar_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-gar_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-gar_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sly-gar_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-gar_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sly-gar_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-gar_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-gar_Angiosperm/kaks_sly-gar_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-pvu_Spermatophyta/kaks_sly-pvu_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-pvu_Spermatophyta/kaks_sbi-pvu_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/sbi-gar_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-gar_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-gar_Angiosperm/kaks_sbi-gar_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-pvu_Angiosperm/kaks_sbi-pvu_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sly.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sly.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/sly-pvu_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sly-pvu_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sly-pvu_Angiosperm/kaks_sly-pvu_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-ata_Chloroplastida/kaks_sbi-ata_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-ata_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-ata_Embryophyta/kaks_sbi-ata_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-ata_Spermatophyta/kaks_sbi-ata_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-pvu_Chloroplastida/kaks_osa-pvu_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/sbi.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/sbi.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/sbi-ata_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/sbi-ata_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/sbi-ata_Angiosperm/kaks_sbi-ata_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/osa-gar_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/osa-gar_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-gar_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-gar_Chloroplastida/kaks_osa-gar_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/pvu.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/pvu.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/pvu-ata_Chloroplastida/kaks_pvu-ata_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-pvu_Chloroplastida/kaks_gar-pvu_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-pvu_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-pvu_Embryophyta/kaks_osa-pvu_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/gar-ata_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/gar-ata_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-ata_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-ata_Chloroplastida/kaks_gar-ata_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-pvu_Spermatophyta/kaks_osa-pvu_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/pvu.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/pvu.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/pvu-ata_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/pvu-ata_Embryophyta/kaks_pvu-ata_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/osa-gar_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/osa-gar_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-gar_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-gar_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-gar_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-gar_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/osa-gar_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-gar_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/osa-gar_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-gar_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-gar_Embryophyta/kaks_osa-gar_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/osa-pvu_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-pvu_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-pvu_Angiosperm/kaks_osa-pvu_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/osa-gar_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/osa-gar_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-gar_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-gar_Spermatophyta/kaks_osa-gar_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/pvu.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/pvu.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/pvu-ata_Spermatophyta/kaks_pvu-ata_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/gar-ata_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/gar-ata_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-ata_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-ata_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-ata_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-ata_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/gar-ata_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-ata_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/gar-ata_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-ata_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-ata_Embryophyta/kaks_gar-ata_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/gar.fa >../associated_data/KaKs_m6A/osa-gar_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/gar.fa >../associated_data/KaKs_m6A/osa-gar_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-gar_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-gar_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-gar_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-gar_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/osa-gar_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-gar_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/osa-gar_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-gar_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-gar_Angiosperm/kaks_osa-gar_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/pvu.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/pvu.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/pvu-ata_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/pvu-ata_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/pvu-ata_Angiosperm/kaks_pvu-ata_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-pvu_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-pvu_Embryophyta/kaks_gar-pvu_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/osa-ata_Chloroplastida/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/osa-ata_Chloroplastida/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/output -f axt
ls ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/output/%  -o ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-ata_Chloroplastida/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-ata_Chloroplastida/kaks_osa-ata_Chloroplastida_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/gar-ata_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/gar-ata_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-ata_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-ata_Spermatophyta/kaks_gar-ata_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-pvu_Spermatophyta/kaks_gar-pvu_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/gar-ata_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/gar-ata_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-ata_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-ata_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-ata_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-ata_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/gar-ata_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-ata_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/gar-ata_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-ata_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-ata_Angiosperm/kaks_gar-ata_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/gar.fa ../associated_data/pep_cds/cds/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/gar.fa ../associated_data/pep_cds/pep/pvu.fa >../associated_data/KaKs_m6A/gar-pvu_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/gar-pvu_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/gar-pvu_Angiosperm/kaks_gar-pvu_Angiosperm_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/osa-ata_Embryophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/osa-ata_Embryophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-ata_Embryophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-ata_Embryophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-ata_Embryophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-ata_Embryophyta/output -f axt
ls ../associated_data/KaKs_m6A/osa-ata_Embryophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-ata_Embryophyta/output/%  -o ../associated_data/KaKs_m6A/osa-ata_Embryophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-ata_Embryophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-ata_Embryophyta/kaks_osa-ata_Embryophyta_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/osa-ata_Spermatophyta/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/osa-ata_Spermatophyta/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/output -f axt
ls ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/output/%  -o ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-ata_Spermatophyta/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-ata_Spermatophyta/kaks_osa-ata_Spermatophyta_out.txt
cat ../associated_data/pep_cds/cds/osa.fa ../associated_data/pep_cds/cds/ata.fa >../associated_data/KaKs_m6A/osa-ata_Angiosperm/spp_merge_cds.fa
cat ../associated_data/pep_cds/pep/osa.fa ../associated_data/pep_cds/pep/ata.fa >../associated_data/KaKs_m6A/osa-ata_Angiosperm/spp_merge_pep.fa
../tools/ParaAT2.0/ParaAT.pl -h ../associated_data/KaKs_m6A/osa-ata_Angiosperm/gene_pairs.txt -a ../associated_data/KaKs_m6A/osa-ata_Angiosperm/spp_merge_pep.fa  -n ../associated_data/KaKs_m6A/osa-ata_Angiosperm/spp_merge_cds.fa -p proc -o ../associated_data/KaKs_m6A/osa-ata_Angiosperm/output -f axt
ls ../associated_data/KaKs_m6A/osa-ata_Angiosperm/output | grep '.axt' | parallel -I% ../tools/KaKs_Calculator -i ../associated_data/KaKs_m6A/osa-ata_Angiosperm/output/%  -o ../associated_data/KaKs_m6A/osa-ata_Angiosperm/output/%.kaks -m MA
cat ../associated_data/KaKs_m6A/osa-ata_Angiosperm/output/*.kaks | awk '{if(!(NR>1&&$1~/Sequence/)){print $0}}' >../associated_data/KaKs_m6A/osa-ata_Angiosperm/kaks_osa-ata_Angiosperm_out.txt
